academico_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: academicoBundle:Default:index }


estudiante_registro:
    pattern:  /secretaria/estudiante/registro
    defaults: { _controller: academicoBundle:default:registroEstudiante}
    
estudiante_requisito:
    pattern:  /secretaria/estudiante/requisito/{cedula}
    defaults: { _controller: academicoBundle:default:requisitoEstudiante}
        
estudiante_registro_p:
    pattern:  /secretaria/estudiante/registro/{cedula}
    defaults: { _controller: academicoBundle:default:registroEstudiantep}    
    
estudiante_busqueda:
    pattern:  /secretaria/estudiante/consulta/inscripcion
    defaults: { _controller: academicoBundle:default:buscarEst}
            
docente_dictadomateria:
    pattern:  /docente/materias
    defaults: { _controller: academicoBundle:default:dictadomateria}
   
estudiante_matricula:
    pattern:  /secretaria/estudiante/matricula/{cedula}
    defaults: { _controller: academicoBundle:default:matriculaEstudiante} 
    
estudiante_buscar:
    pattern:  /secretaria/estudiante/consulta/matricula
    defaults: { _controller: academicoBundle:default:matriculaBuscarEstudiante}      