academico_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: academicoBundle:Default:index }

_portada:    
    pattern:  /inicio
    defaults: {_controller: academicoBundle:Default:portada }

estudiante_registro:
    pattern:  /estudiante/registro
    defaults: { _controller: academicoBundle:default:registroEstudiante}
    
estudiante_requisito:
    pattern:  /estudiante/requisito
    defaults: { _controller: academicoBundle:default:requisitoEstudiante}
        
estudiante_registro_p:
    pattern:  /estudiante/registro/{cedula}
    defaults: { _controller: academicoBundle:default:registroEstudiantep}    
    
estudiante_busqueda:
    pattern:  /estudiante/consulta/inscripcion
    defaults: { _controller: academicoBundle:default:buscarEst}
    
estudiante_buscar:
    pattern:  /estudiante/consulta/matricula
    defaults: { _controller: academicoBundle:default:buscarE}    