academico_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: academicoBundle:Default:index }

estudiante_registro:
    pattern:  /secretaria/estudiante/registro
    defaults: { _controller: academicoBundle:default:registroEstudiante}
    
estudiante_requisito:
    pattern:  /secretaria/estudiante/requisito/{cedula}
    defaults: { _controller: academicoBundle:default:requisitoEstudiante}
        
estudiante_registro_p:
    pattern:  /secretaria/estudiante/registro/{cedula}
    defaults: { _controller: academicoBundle:default:registroEstudiantep}    
    
estudiante_busqueda:
    pattern:  /secretaria/estudiante/consulta/inscripcion
    defaults: { _controller: academicoBundle:default:buscarEst}
            
amaterias_dictadomateria:
    pattern:  /pedagogico/materias
    defaults: { _controller: academicoBundle:default:dictadomateria}
    
amaterias_lista_materias_asignadas:
    pattern:  /pedagogico/lista/materias-asignadas
    defaults: { _controller: academicoBundle:default:listadictadomateria}
    
amaterias_modificar_materias_asignadas:
    pattern:  /pedagogico/modificar/materias-asignadas/{codm}
    defaults: { _controller: academicoBundle:default:modificardictadomateria}    
    
amaterias_eliminar_materias_asignadas:
    pattern:  /pedagogico/eliminar/materias-asignadas
    defaults: { _controller: academicoBundle:default:eliminardictadomateria}    
   
estudiante_matricula:
    pattern:  /secretaria/estudiante/matricula/{cedula}
    defaults: { _controller: academicoBundle:default:matriculaEstudiante} 
    
estudiante_buscar:
    pattern:  /secretaria/estudiante/consulta/matricula
    defaults: { _controller: academicoBundle:default:matriculaBuscarEstudiante}      
    
docente_notas_x_materia:
    pattern:  /docente/notas/parciales/lista/estudiantes/{mesid}/{niv}/{mat}
    defaults: { _controller: academicoBundle:default:notas}
     
estudiante_lista_inscritos:
    pattern:  /secretaria/estudiante/lista/inscritos
    defaults: { _controller: academicoBundle:default:listaestudiantesinscritos}
    
estudiante_modificar_datos:
    pattern:  /secretaria/estudiante/modificar/{cedula}
    defaults: { _controller: academicoBundle:default:modificarestudiante}
        
estudiante_lista_matriculados_x_secciones:   
    pattern:  /secretaria/estudiante/lista/matriculados/{nivel}
    defaults: { _controller: academicoBundle:default:listaestudiantesxsecciones}
    
estudiante_matriculado_modificar:   
    pattern:  /secretaria/estudiante/matriculado/modificar/{mid}
    defaults: { _controller: academicoBundle:default:modificarmatricula}    
    
estudiante_lista_matriculados_x_materia_x_secciones:   
    pattern:  /inspector/estudiante/lista/materias/{materias}/{nivel}
    defaults: { _controller: academicoBundle:default:listaestudiantesxseccionesmateria}
    
lista_materia_x_nivel:    
    pattern:  /inspector/lista/materias/{nivel}
    defaults: { _controller: academicoBundle:default:listamateriasxnivel}    

docente_lista_materias_suspenso:    
    pattern:  /docente/notas/suspenso/lista/estudiantes/{niv}/{mat}
    defaults: { _controller: academicoBundle:default:notasuspenso} 
#delete    
docente_notas_suspenso:    
    pattern:  /docente/notas/suspenso/lista/estudiantes
    defaults: { _controller: academicoBundle:default:notasuspenso} 
    
docente_variable_sesion:    
    pattern:  /docente/portada/{niv}/{mat}
    defaults: { _controller: academicoBundle:default:sesionportada}    

docente_notas_parciales_x_mes:    
    pattern:  /docente/notas/parciales/mes/{codmes}/{niv}/{mat}
    defaults: { _controller: academicoBundle:default:notasparcialesxmes}
      
docente_acta_general_calificaciones_estudiantes:    
    pattern:  /docente/acta/general/estudiantes/{niv}/{mat}
    defaults: { _controller: academicoBundle:default:actageneralcalificacionesestudiantes}
    
inspector_horario_asignar:
    pattern:  /inspector/horario-clases/asignar/{did}
    defaults: { _controller: academicoBundle:default:horarioclase}    
    
docente_ver_horario:    
    pattern:  /docente/ver/horario/docente
    defaults: { _controller: academicoBundle:default:verhorariodocente}        
    
inspector_lista_materiasgrado_x_nivel:    
    pattern:  /inspector/materias/grado/lista/{codniv}
    defaults: { _controller: academicoBundle:default:listamateriasgrado}    
    
inspector_examengrado_registro_notas:
    pattern:  /inspector/examenes/grado/notas/{codmg}
    defaults: { _controller: academicoBundle:default:notasgrado }            
    
secretaria_requisito_listar_todos:    
    pattern:  /secretaria/consulta/requisitos/lista
    defaults: { _controller: academicoBundle:default:listatodosrequisitos }            
    
modificar_perfil:
    pattern:  /{rol}/modificar/perfil
    defaults: { _controller: academicoBundle:default:modificarperfildocente}    
    
    
acta_general_calificaciones_reporte:
    pattern:  /docente/acta/general/reporte
    defaults: { _controller: academicoBundle:default:reporteactageneralcalificacionesestudiantes, _format: pdf}    
    requirements:
        _format: html|pdf
       
docente_reporte_notas_supletorios:
    pattern:  /docente/reporte/notas/supletorios/{nid}/{mid}
    defaults: { _controller: academicoBundle:default:reportenotassuspenso, _format: pdf}    
    requirements:
        _format: pdf                
        
docente_reporte_notas_parciales_x_mes:
    pattern:  /docente/reporte/notas/parciale/mes/{mesid}/{nid}/{mid}
    defaults: { _controller: academicoBundle:default:reportenotasparcialesxmes, _format: pdf}    
    requirements:
        _format: html|pdf                                