parameters:
    database_driver: pdo_sqlsrv
    database_host: 127.0.0.1
    database_port: '1433'
    database_name: bdconduespoch4
    database_user: yonynet
    database_password: qwerty
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    database_path: null
