seguridad:
    resource: "@seguridadBundle/Resources/config/routing.yml"
    prefix:   /

administrativo:
    resource: "@administrativoBundle/Resources/config/routing.yml"
    prefix:   /

academico:
    resource: "@academicoBundle/Resources/config/routing.yml"
    prefix:   /

_portada:    
    pattern:  /inicio
    defaults: {_controller: academicoBundle:Default:portada }

portada:
    path:    /{role}
    defaults: {_controller: seguridadBundle:Default:portada, role: null }    
