security:
  
    firewalls:
        frontend:
            pattern: ^/*
            #hace que no todos los usuarios que ingresen a la pagina web tengan que loguearse
            anonymous: ~
            #Tipo autenticacion: muestra formulario pidiendo usuario y contraseña
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /inicio
            #cierro sesion
            logout:
                path: usuario_logout
                target: /inicio
            #cambiar de usuarios
            switch_user:  true
                
            remember_me:
                #valor aleatorio para codificar la cookie
                key:      conduespoch2014 
                # tiempo en segundos que el usuario permanece logueado sin que le pida la contraseña
                lifetime: 3600
            
    #opciones de autorizacion
    access_control:
        - { path: ^/secretaria/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secretaria/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secretaria/*, roles: ROLE_SECRETARIA }
        - { path: ^/docente/*, roles: ROLE_DOCENTE }
        - { path: ^/inspector/*, roles: ROLE_INSPECTOR }
        - { path: ^/amaterias/*, roles: ROLE_AMATERIAS }
        
   #encargados de crear los usuarios de la aplicacion
    providers:      
        usuarios:
            entity: { class: Acad\seguridadBundle\Entity\Usuario, property: email }
            
    #codificacion de contraseñas        
    encoders:
        Acad\seguridadBundle\Entity\Usuario: { algorithm: sha512, iterations: 10  }
