parameters:
#    seguridad.example.class: Acad\seguridadBundle\Example

services:
#    seguridad.example:
#        class: %seguridad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
