parameters:
#    usuario.example.class: Cupon\UsuarioBundle\Example

services:
    login_listener:
        class:  Acad\seguridadBundle\Listener\LoginListener        
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
