administrativo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: administrativoBundle:Default:index }

docente_registro:
    pattern:  /docente/registro
    defaults: { _controller: administrativoBundle:Default:registrodocente}
    
periodo_registro:
    pattern:  /admin/periodo/registro
    defaults: { _controller: administrativoBundle:Default:registroperiodo}    
    
mes_evaluacion:
    pattern:  /admin/mes/evaluacion/{pid}
    defaults: { _controller: administrativoBundle:Default:mesevaluacion}
    
admin_portada:
    pattern:  /admin/portada
    defaults: { _controller: administrativoBundle:Default:portada}    