administrativo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: administrativoBundle:Default:index }

docente_registro:
    pattern:  /admin/docente/registro
    defaults: { _controller: administrativoBundle:Default:registrodocente}
    
periodo_registro:
    pattern:  /admin/periodo/registro
    defaults: { _controller: administrativoBundle:Default:registroperiodo}    

periodo_modificar:
    pattern:  /admin/periodo/modificar
    defaults: { _controller: administrativoBundle:Default:periodomodificar}            
    
mes_evaluacion:
    pattern:  /admin/mes/evaluacion/{pid}
    defaults: { _controller: administrativoBundle:Default:mesevaluacion}
    
admin_portada:
    pattern:  /admin/portada
    defaults: { _controller: administrativoBundle:Default:portada}    

admin_mes_registro:
    pattern:  /admin/parcial/registro
    defaults: { _controller: administrativoBundle:Default:registromes}    

admin_mes_listar_todos:
    pattern:  /admin/parcial/lista
    defaults: { _controller: administrativoBundle:Default:listatodosmeses}        

admin_mes_modificar:
    pattern:  /admin/parcial/modificar/{codmes}
    defaults: { _controller: administrativoBundle:Default:mesmodicar}            

admin_mes_modificar_todos:
    pattern:  /admin/parcial/cambiar/estados
    defaults: { _controller: administrativoBundle:Default:mesmodicartodos}     

admin_nivel_registro:
    pattern:  /admin/nivel/registro
    defaults: { _controller: administrativoBundle:Default:nivelregistro}                
    
admin_nivel_listar_todos:
    pattern:  /admin/nivel/lista
    defaults: { _controller: administrativoBundle:Default:listatodosniveles}            
    
admin_nivel_modificar:
    pattern:  /admin/nivel/modificar/{codnivel}
    defaults: { _controller: administrativoBundle:Default:nivelmodicar}               

admin_requisito_registro:
    pattern:  /admin/requisito/registro
    defaults: { _controller: administrativoBundle:Default:requisitoregistro}                    
    
admin_requisito_listar_todos:
    pattern:  /admin/requisito/lista
    defaults: { _controller: administrativoBundle:Default:listatodosrequisitos}                
    
admin_requisito_modificar:
    pattern:  /admin/requisito/modificar/{codreq}
    defaults: { _controller: administrativoBundle:Default:requisitomodicar}                   
    
admin_requisito_modificar_estados:
    pattern:  /admin/requisito/modificar-todos/lista
    defaults: { _controller: administrativoBundle:Default:requisitomodicarestados}                           
    
area_ingresar:
    pattern:  /admin/area/ingresar
    defaults: { _controller: administrativoBundle:Default:areaIngresar}
    
area_modificar:    
    pattern:  /admin/area/listar
    defaults: { _controller: administrativoBundle:Default:listaareaModificar}
    
area_modificar_id:    
    pattern:  /admin/area/modificar/{aid}
    defaults: { _controller: administrativoBundle:Default:areaModificar}    
    
curso_ingresar:
    pattern:  /admin/curso/ingresar
    defaults: { _controller: administrativoBundle:Default:cursoIngresar}
    
curso_modificar:    
    pattern:  /admin/curso/listar
    defaults: { _controller: administrativoBundle:Default:listacursoModificar}
    
curso_modificar_id:    
    pattern:  /admin/curso/modificar/{cid}
    defaults: { _controller: administrativoBundle:Default:cursoModificar}     
    
    
docente_ingresar:
    pattern:  /admin/docente/ingresar
    defaults: { _controller: administrativoBundle:Default:registrodocente}
    
docente_modificar:    
    pattern:  /admin/docente/listar
    defaults: { _controller: administrativoBundle:Default:listadocenteModificar}
    
docente_modificar_id:    
    pattern:  /admin/docente/modificar/{did}
    defaults: { _controller: administrativoBundle:Default:docenteModificar}        
    
hora_ingresar:
    pattern:  /admin/hora/ingresar
    defaults: { _controller: administrativoBundle:Default:horaIngresar}
    
hora_modificar:    
    pattern:  /admin/hora/listar
    defaults: { _controller: administrativoBundle:Default:listahoraModificar}
    
hora_modificar_id:    
    pattern:  /admin/hora/modificar/{hid}
    defaults: { _controller: administrativoBundle:Default:horaModificar}
    
materia_ingresar:
    pattern:  /admin/materia/ingresar
    defaults: { _controller: administrativoBundle:Default:materiaIngresar}
    
materia_modificar:    
    pattern:  /admin/materia/listar
    defaults: { _controller: administrativoBundle:Default:listamateriaModificar}
    
materia_modificar_id:    
    pattern:  /admin/materia/modificar/{mid}
    defaults: { _controller: administrativoBundle:Default:materiaModificar}    
    
materia_modificar_todos:    
    pattern:  /admin/materias/modificar/todos
    defaults: { _controller: administrativoBundle:Default:materiaModificartodos}
    
usuario_modificar:    
    pattern:  /admin/usuario/listar
    defaults: { _controller: administrativoBundle:Default:listausuarioModificar}
    
usuario_modificar_id:    
    pattern:  /admin/usuario/modificar/{uid}
    defaults: { _controller: administrativoBundle:Default:usuarioModificar}      

admin_paralelo_registro:
    pattern:  /admin/paralelo/registro
    defaults: { _controller: administrativoBundle:Default:paraleloregistro}

admin_paralelo_modificar:
    pattern:  /admin/paralelo/modificar/{codpar}
    defaults: { _controller: administrativoBundle:Default:paralelomodificar}    
    
admin_paralelo_listar_todos:
    pattern:  /admin/paralelo/listar
    defaults: { _controller: administrativoBundle:Default:listatodosparalelos}        

admin_dia_registro:
    pattern:  /admin/dias/registro
    defaults: { _controller: administrativoBundle:Default:diaregistro}    
    
admin_dia_modificar:
    pattern:  /admin/dias/modificar/{coddia}
    defaults: { _controller: administrativoBundle:Default:diamodificar}        
    
admin_dia_listar_todos:
    pattern:  /admin/dias/lista
    defaults: { _controller: administrativoBundle:Default:listartodosdias}            
    
admin_materiagrado_registro:    
    pattern:  /admin/materia/grado/registro
    defaults: { _controller: administrativoBundle:Default:materiagradoregistrar }            
    
admin_materiagrado_modificar:    
    pattern:  /admin/materia/grado/modificar/{codmg}
    defaults: { _controller: administrativoBundle:Default:materiagradomodificar }                
    
admin_materiagrado_listar_todos:    
    pattern:  /admin/materia/grado/lista
    defaults: { _controller: administrativoBundle:Default:materiagradolistatodos }                
     
admin_configuracion_general:
    pattern:  /admin/configuracion/general
    defaults: { _controller: administrativoBundle:Default:configuraciongeneral}    
        
admin_configuracion_actual:
    pattern:  /admin/configuracion/actual
    defaults: { _controller: administrativoBundle:Default:configuracionactual}    
                
admin_subperiodo_registro:                
    pattern:  /admin/subperiodo/registro
    defaults: { _controller: administrativoBundle:Default:subperiodoregistro}    
    
admin_subperiodo_modificar:                
    pattern:  /admin/subperiodo/modificar/{sid}
    defaults: { _controller: administrativoBundle:Default:subperiodomodificar}        
    
admin_subperiodo_listar_todos:                
    pattern:  /admin/subperiodo/lista
    defaults: { _controller: administrativoBundle:Default:subperiodolistartodos}            
                
admin_materiaperiodo_registro:                
    pattern:  /admin/materia-periodo/registro
    defaults: { _controller: administrativoBundle:Default:materiaperiodoregistro}    
    
admin_materiaperiodo_modificar:                
    pattern:  /admin/materia-periodo/modificar/{mpid}
    defaults: { _controller: administrativoBundle:Default:materiaperiodomodificar}        
    
admin_materiaperiodo_listar_todos:                
    pattern:  /admin/materia-periodo/lista
    defaults: { _controller: administrativoBundle:Default:materiaperiodolistartodos}                            
    
admin_materiaperiodo_modificar_todos:    
    pattern:  /admin/materias-periodo/modificar/todos
    defaults: { _controller: administrativoBundle:Default:materiaperiodoModificartodos}    
    
admin_rol_registro:                
    pattern:  /admin/rol/registro
    defaults: { _controller: administrativoBundle:Default:rolregistro}    
    
admin_rol_modificar:                
    pattern:  /admin/rol/modificar/{rid}
    defaults: { _controller: administrativoBundle:Default:rolmodificar}        
    
admin_rol_listar_todos:                
    pattern:  /admin/rol/listar/todos
    defaults: { _controller: administrativoBundle:Default:rollistartodos}                