parameters:
#    administrativo.example.class: Acad\administrativoBundle\Example

services:
#    administrativo.example:
#        class: %administrativo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
