<?php

namespace Proxies\__CG__\Acad\academicoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Asistencia extends \Acad\academicoBundle\Entity\Asistencia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setHorasmodulo($horasmodulo)
    {
        $this->__load();
        return parent::setHorasmodulo($horasmodulo);
    }

    public function getHorasmodulo()
    {
        $this->__load();
        return parent::getHorasmodulo();
    }

    public function setFaltasjustificadas($faltasjustificadas)
    {
        $this->__load();
        return parent::setFaltasjustificadas($faltasjustificadas);
    }

    public function getFaltasjustificadas()
    {
        $this->__load();
        return parent::getFaltasjustificadas();
    }

    public function setFaltasinjustificadas($faltasinjustificadas)
    {
        $this->__load();
        return parent::setFaltasinjustificadas($faltasinjustificadas);
    }

    public function getFaltasinjustificadas()
    {
        $this->__load();
        return parent::getFaltasinjustificadas();
    }

    public function setAtrasos($atrasos)
    {
        $this->__load();
        return parent::setAtrasos($atrasos);
    }

    public function getAtrasos()
    {
        $this->__load();
        return parent::getAtrasos();
    }

    public function setHorasasistidas($horasasistidas)
    {
        $this->__load();
        return parent::setHorasasistidas($horasasistidas);
    }

    public function getHorasasistidas()
    {
        $this->__load();
        return parent::getHorasasistidas();
    }

    public function setObservaciones($observaciones)
    {
        $this->__load();
        return parent::setObservaciones($observaciones);
    }

    public function getObservaciones()
    {
        $this->__load();
        return parent::getObservaciones();
    }

    public function setPromediofinal($promediofinal)
    {
        $this->__load();
        return parent::setPromediofinal($promediofinal);
    }

    public function getPromediofinal()
    {
        $this->__load();
        return parent::getPromediofinal();
    }

    public function setSuspenso($suspenso)
    {
        $this->__load();
        return parent::setSuspenso($suspenso);
    }

    public function getSuspenso()
    {
        $this->__load();
        return parent::getSuspenso();
    }

    public function setNotagrado($notagrado)
    {
        $this->__load();
        return parent::setNotagrado($notagrado);
    }

    public function getNotagrado()
    {
        $this->__load();
        return parent::getNotagrado();
    }

    public function setPromediototal($promediototal)
    {
        $this->__load();
        return parent::setPromediototal($promediototal);
    }

    public function getPromediototal()
    {
        $this->__load();
        return parent::getPromediototal();
    }

    public function setMateriaasiganda(\Acad\academicoBundle\Entity\MateriaAsignada $materiaasiganda = NULL)
    {
        $this->__load();
        return parent::setMateriaasiganda($materiaasiganda);
    }

    public function getMateriaasiganda()
    {
        $this->__load();
        return parent::getMateriaasiganda();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'horasmodulo', 'faltasjustificadas', 'faltasinjustificadas', 'atrasos', 'horasasistidas', 'observaciones', 'promediofinal', 'suspenso', 'notagrado', 'promediototal', 'materiaasiganda');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}